server:
  port: 8080
  forward-headers-strategy: framework

logging:
  level:
    org.springframework.web: WARN
    com.datastax.astra: INFO
    root: WARN

spring:
  data:
    cassandra:
      schema-action: CREATE_IF_NOT_EXISTS

astra:
  api:
    application-token: ${ASTRA_DB_APPLICATION_TOKEN}
    database-id: ${ASTRA_DB_ID}
    database-region: ${ASTRA_DB_REGION}
  cql:
    enabled: true
    download-scb:
      enabled: true
    driver-config:
      basic:
        session-keyspace: ${ASTRA_DB_KEYSPACE}
  metrics:
    enabled: true